In [1]:
import numpy as np
import pandas as pd

Dataframe is a combination of multiple Series.

Creation of dataframe

In [10]:
dataDict = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

dfD = pd.DataFrame(dataDict)
dfD

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
dataList = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
dataCol = ['Name', 'Age', 'City', 'Salary']

dfL = pd.DataFrame(dataList, columns=dataCol)
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and idexing of Columns

In [24]:
dfL['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [25]:
dfL[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [26]:
dfL['Designation'] = ['HR', 'SDE', 'Engineer', 'Doctor']

In [27]:
dfL

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         SDE
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

Removing a column

In [29]:
dfL.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
dfL

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         SDE
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000      Doctor

In [31]:
dfL.drop('Designation', axis=1, inplace=True)

In [32]:
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
dfL.drop(['Age', 'Salary'], axis=1)

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [34]:
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
dfL.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [36]:
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting Rows

In [37]:
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
dfL.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [39]:
dfL['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [40]:
dfL.loc[[0, 1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

Selecting subsets of rows and columns

In [41]:
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [46]:
dfL.loc[[0, 1], ['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [51]:
dfL[['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000
3    London   85000

In [52]:
dfL.loc[[2,3], ['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [53]:
dfL

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

People with age above 30

In [56]:
dfL[dfL['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

People with age above 30 and city must be paris

In [57]:
dfL[(dfL['Age'] > 30) & (dfL['City'] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000