In [1]:
import numpy as np
import pandas as pd

## Handling missing data

Identifying missing data

In [36]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

In [37]:
dataF = pd.DataFrame(data)
dataF

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [38]:
dataF.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [39]:
dataF.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [40]:
dataF.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing missing data

In [41]:
dataF

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [42]:
dataF.dropna() #works in rows

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [43]:
dataF.dropna(thresh=3) #The thresh value means minimum number of non 
# null values should be equal to the thresh value
# works in rows

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

Filling the missing data

In [44]:
dataF

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [45]:
dataF.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [46]:
values = {'A': 0, 'B': 100, 'C': 200, 'D': 300}
dataF.fillna(value=values) # fills column wise

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  300.0
2  0.0    3.0    3.0  300.0
3  4.0    4.0  200.0  300.0
4  5.0    5.0  200.0    5.0

In [47]:
dataF.fillna(dataF.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0